# Generated by Django 6.0.6 on 2026-06-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
